import { z } from "zod";

export const workflowTypeEnum = z.enum(["type1", "type2", "type3"]); // Replace with actual workflow types
export const priorityEnum = z.enum(["1", "2", "3"]); // Priority levels: 1=Low, 2=Medium, 3=High

export const masterOrderSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(), // Autogenerated in backend
  project_name: z.string().min(1),
  workflow_type: workflowTypeEnum.optional(),
  client_id: z.number().optional(),
  vendor_id: z.boolean().optional(),
  date_order: z.string().min(1).optional(),
  date_expected: z.string().min(1).optional(),
  priority: priorityEnum.optional(),
  amount_total: z.number().optional(),
  line_ids: z.array(z.string()).optional(),
});

export type MasterOrder = z.infer<typeof masterOrderSchema>;
